export const GET_IP_GEOCODE = 'GET_IP_GEOCODE';
export const GET_IP_GEOCODE_PASS = 'GET_IP_GEOCODE_PASS';
export const GET_IP_GEOCODE_FAIL = 'GET_IP_GEOCODE_FAIL';
export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_PASS = 'GET_WEATHER_PASS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';
export const GET_WEATHER_CURRENT = 'GET_WEATHER_CURRENT';
export const GET_WEATHER_CURRENT_PASS = 'GET_WEATHER_CURRENT_PASS';
export const GET_WEATHER_CURRENT_FAIL = 'GET_WEATHER_CURRENT_FAIL';
export const GET_WEATHER_FORECAST = 'GET_WEATHER_FORECAST';
export const GET_WEATHER_FORECAST_PASS = 'GET_WEATHER_FORECAST_PASS';
export const GET_WEATHER_FORECAST_FAIL = 'GET_WEATHER_FORECAST_FAIL';
export const UPDATE_WEATHER_STATE = 'UPDATE_WEATHER_STATE';

export const OPENWEATHER_URL = 'https://api.openweathermap.org/data/2.5'
